# Generated by Django 3.1.1 on 2020-10-07 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OMVOiG_reestr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=250, verbose_name='Фамилия, имя, отчество')),
                ('job_description', models.CharField(default='', max_length=250, verbose_name='Должность')),
                ('date_settling', models.DateField(verbose_name='Дата трудоустройства')),
                ('dogovor', models.CharField(default='', max_length=250, verbose_name='Основание для привлечения личного труда')),
                ('responsibility', models.CharField(default='', max_length=250, verbose_name='Выполняемые функции, проводые исследования')),
                ('education', models.CharField(default='', max_length=250, verbose_name='Образование')),
                ('experience', models.CharField(default='', max_length=250, verbose_name='Опыт работы')),
                ('attestation_date_protocol', models.CharField(default='', max_length=250, verbose_name='Дата и номер протокола аттестации, периодичность аттестации')),
                ('qualification_up', models.TextField(default='-', verbose_name='Сведения о повышении квалификации')),
                ('date_job_describ', models.DateField(verbose_name='Дата утверждения должностной инструкции')),
                ('group', models.CharField(default='', max_length=250, verbose_name='Наименование группы')),
                ('information', models.CharField(default='', max_length=250, verbose_name='Примечание')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
