# Generated by Django 3.1.1 on 2020-10-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omvoig_reestr',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Реестр ОМВОиГ'},
        ),
        migrations.RemoveField(
            model_name='omvoig_reestr',
            name='user',
        ),
        migrations.AddField(
            model_name='omvoig_reestr',
            name='image_of_person',
            field=models.ImageField(blank=True, null=True, upload_to='images/omvoig_reestr/'),
        ),
        migrations.AlterField(
            model_name='omvoig_reestr',
            name='group',
            field=models.CharField(choices=[('Группа анализа природных и питьевых вод', 'Группа анализа природных и питьевых вод'), ('Группа хроматографических и спектрометрических исследований', 'Группа хроматографических и спектрометрических исследований'), ('Группа анализа грунтов', 'Группа анализа грунтов'), ('Группа токсикологических исследований', 'Группа токсикологических исследований')], default='', max_length=250, verbose_name='Наименование группы'),
        ),
    ]
