# Generated by Django 3.1.1 on 2020-10-08 12:35

from django.db import migrations, models
import reestr_people.models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr_people', '0002_auto_20201008_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMFF_reestr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=250, verbose_name='Фамилия, имя, отчество')),
                ('job_description', models.CharField(default='', max_length=250, verbose_name='Должность')),
                ('date_settling', models.DateField(verbose_name='Дата трудоустройства')),
                ('dogovor', models.CharField(default='', max_length=250, verbose_name='Основание для привлечения личного труда')),
                ('responsibility', models.CharField(default='', max_length=250, verbose_name='Выполняемые функции, проводые исследования')),
                ('education', models.CharField(default='', max_length=250, verbose_name='Образование')),
                ('experience', models.CharField(default='', max_length=250, verbose_name='Опыт работы')),
                ('attestation_date_protocol', models.CharField(default='', max_length=250, verbose_name='Дата и номер протокола аттестации, периодичность аттестации')),
                ('qualification_up', models.TextField(default='-', verbose_name='Сведения о повышении квалификации')),
                ('date_job_describ', models.DateField(verbose_name='Дата утверждения должностной инструкции')),
                ('group', models.CharField(choices=[('Группа радиационного контроля', 'Группа радиационного контроля'), ('В отделе', 'В отделе')], default='-', max_length=250, verbose_name='Наименование группы')),
                ('information', models.CharField(default='', max_length=250, verbose_name='Примечание')),
                ('image_of_person', models.ImageField(blank=True, null=True, upload_to=reestr_people.models.directory_path_to_reestr_personal_OMFF_img)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Реестр ОМФФ',
            },
        ),
        migrations.AlterField(
            model_name='omvoig_reestr',
            name='image_of_person',
            field=models.ImageField(blank=True, null=True, upload_to=reestr_people.models.directory_path_to_reestr_personal_OMVOIG_img),
        ),
    ]
