# Generated by Django 3.1.1 on 2020-10-09 04:00

from django.db import migrations, models
import reestr_people.models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr_people', '0004_auto_20201009_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHTI_reestr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=250, verbose_name='Фамилия, имя, отчество')),
                ('job_description', models.CharField(default='', max_length=250, verbose_name='Должность')),
                ('date_settling', models.DateField(verbose_name='Дата трудоустройства')),
                ('dogovor', models.CharField(default='', max_length=250, verbose_name='Основание для привлечения личного труда')),
                ('responsibility', models.CharField(default='', max_length=250, verbose_name='Выполняемые функции, проводые исследования')),
                ('education', models.CharField(default='', max_length=250, verbose_name='Образование')),
                ('experience', models.CharField(default='', max_length=250, verbose_name='Опыт работы')),
                ('attestation_date_protocol', models.CharField(default='', max_length=250, verbose_name='Дата и номер протокола аттестации, периодичность аттестации')),
                ('qualification_up', models.TextField(default='-', verbose_name='Сведения о повышении квалификации')),
                ('date_job_describ', models.DateField(verbose_name='Дата утверждения должностной инструкции')),
                ('information', models.CharField(default='', max_length=250, verbose_name='Примечание')),
                ('image_of_person', models.ImageField(blank=True, null=True, upload_to=reestr_people.models.directory_path_to_reestr_personal_OHTI_img)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Реестр ОХТИ',
            },
        ),
    ]
