# Generated by Django 3.1.1 on 2020-10-09 05:29

from django.db import migrations, models
import reestr_people.models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr_people', '0005_ohti_reestr'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMOIR_reestr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=250, verbose_name='Фамилия, имя, отчество')),
                ('job_description', models.CharField(default='', max_length=250, verbose_name='Должность')),
                ('date_settling', models.DateField(verbose_name='Дата трудоустройства')),
                ('dogovor', models.CharField(default='', max_length=250, verbose_name='Основание для привлечения личного труда')),
                ('responsibility', models.CharField(default='', max_length=250, verbose_name='Выполняемые функции, проводые исследования')),
                ('education', models.CharField(default='', max_length=250, verbose_name='Образование')),
                ('experience', models.CharField(default='', max_length=250, verbose_name='Опыт работы')),
                ('attestation_date_protocol', models.CharField(default='', max_length=250, verbose_name='Дата и номер протокола аттестации, периодичность аттестации')),
                ('qualification_up', models.TextField(default='-', verbose_name='Сведения о повышении квалификации')),
                ('date_job_describ', models.DateField(verbose_name='Дата утверждения должностной инструкции')),
                ('information', models.CharField(default='', max_length=250, verbose_name='Примечание')),
                ('image_of_person', models.ImageField(blank=True, null=True, upload_to=reestr_people.models.directory_path_to_reestr_personal_OMOIR_img)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Реестр ОМОиР',
            },
        ),
        migrations.CreateModel(
            name='ORIMP_reestr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=250, verbose_name='Фамилия, имя, отчество')),
                ('job_description', models.CharField(default='', max_length=250, verbose_name='Должность')),
                ('date_settling', models.DateField(verbose_name='Дата трудоустройства')),
                ('dogovor', models.CharField(default='', max_length=250, verbose_name='Основание для привлечения личного труда')),
                ('responsibility', models.CharField(default='', max_length=250, verbose_name='Выполняемые функции, проводые исследования')),
                ('education', models.CharField(default='', max_length=250, verbose_name='Образование')),
                ('experience', models.CharField(default='', max_length=250, verbose_name='Опыт работы')),
                ('attestation_date_protocol', models.CharField(default='', max_length=250, verbose_name='Дата и номер протокола аттестации, периодичность аттестации')),
                ('qualification_up', models.TextField(default='-', verbose_name='Сведения о повышении квалификации')),
                ('date_job_describ', models.DateField(verbose_name='Дата утверждения должностной инструкции')),
                ('information', models.CharField(default='', max_length=250, verbose_name='Примечание')),
                ('image_of_person', models.ImageField(blank=True, null=True, upload_to=reestr_people.models.directory_path_to_reestr_personal_ORIMP_img)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Реестр ОРиМР',
            },
        ),
        migrations.CreateModel(
            name='PO_reestr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=250, verbose_name='Фамилия, имя, отчество')),
                ('job_description', models.CharField(default='', max_length=250, verbose_name='Должность')),
                ('date_settling', models.DateField(verbose_name='Дата трудоустройства')),
                ('dogovor', models.CharField(default='', max_length=250, verbose_name='Основание для привлечения личного труда')),
                ('responsibility', models.CharField(default='', max_length=250, verbose_name='Выполняемые функции, проводые исследования')),
                ('education', models.CharField(default='', max_length=250, verbose_name='Образование')),
                ('experience', models.CharField(default='', max_length=250, verbose_name='Опыт работы')),
                ('attestation_date_protocol', models.CharField(default='', max_length=250, verbose_name='Дата и номер протокола аттестации, периодичность аттестации')),
                ('qualification_up', models.TextField(default='-', verbose_name='Сведения о повышении квалификации')),
                ('date_job_describ', models.DateField(verbose_name='Дата утверждения должностной инструкции')),
                ('information', models.CharField(default='', max_length=250, verbose_name='Примечание')),
                ('image_of_person', models.ImageField(blank=True, null=True, upload_to=reestr_people.models.directory_path_to_reestr_personal_PO_img)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Реестр PO',
            },
        ),
        migrations.CreateModel(
            name='RUK_reestr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=250, verbose_name='Фамилия, имя, отчество')),
                ('job_description', models.CharField(default='', max_length=250, verbose_name='Должность')),
                ('date_settling', models.DateField(verbose_name='Дата трудоустройства')),
                ('dogovor', models.CharField(default='', max_length=250, verbose_name='Основание для привлечения личного труда')),
                ('responsibility', models.CharField(default='', max_length=250, verbose_name='Выполняемые функции, проводые исследования')),
                ('education', models.CharField(default='', max_length=250, verbose_name='Образование')),
                ('experience', models.CharField(default='', max_length=250, verbose_name='Опыт работы')),
                ('attestation_date_protocol', models.CharField(default='', max_length=250, verbose_name='Дата и номер протокола аттестации, периодичность аттестации')),
                ('qualification_up', models.TextField(default='-', verbose_name='Сведения о повышении квалификации')),
                ('date_job_describ', models.DateField(verbose_name='Дата утверждения должностной инструкции')),
                ('information', models.CharField(default='', max_length=250, verbose_name='Примечание')),
                ('image_of_person', models.ImageField(blank=True, null=True, upload_to=reestr_people.models.directory_path_to_reestr_personal_RUK_img)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Реестр Руководство',
            },
        ),
    ]
