# Generated by Django 3.1.1 on 2020-10-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reestr_people', '0006_omoir_reestr_orimp_reestr_po_reestr_ruk_reestr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='po_reestr',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Реестр ПO'},
        ),
    ]
