# Generated by Django 3.1.1 on 2020-10-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_description',
            field=models.CharField(default='-', max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='-', max_length=15, verbose_name='Номер телефона'),
        ),
    ]
