# Generated by Django 3.1.1 on 2020-10-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201008_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
