# Generated by Django 3.1.1 on 2020-10-08 10:38

from django.db import migrations, models
import django.db.models.deletion
import reestrOMVOiG.models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr_people', '0002_auto_20201008_1310'),
        ('reestrOMVOiG', '0002_auto_20201008_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_io',
            name='attestation_file',
        ),
        migrations.AddField(
            model_name='equipment_io',
            name='description_type',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_io_description_type, verbose_name='Описание типа'),
        ),
        migrations.AddField(
            model_name='equipment_io',
            name='method_file_poverka',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_io_method_file_poverka, verbose_name='Методика поверки/аттестации'),
        ),
        migrations.AddField(
            model_name='equipment_io',
            name='verification_file',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_io_verification, verbose_name='Файл поверки'),
        ),
        migrations.AddField(
            model_name='equipment_si',
            name='description_type',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_description_type, verbose_name='Описание типа'),
        ),
        migrations.AddField(
            model_name='equipment_si',
            name='method_file_poverka',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_method_file_poverka, verbose_name='Методика поверки/аттестации'),
        ),
        migrations.AddField(
            model_name='equipment_vo',
            name='description_type',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_vo_description_type, verbose_name='Описание типа'),
        ),
        migrations.AddField(
            model_name='equipment_vo',
            name='method_file_poverka',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_vo_method_file_poverka, verbose_name='Методика поверки/аттестации'),
        ),
        migrations.AddField(
            model_name='equipment_vo',
            name='verification_file',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_vo_verification, verbose_name='Файл поверки'),
        ),
        migrations.AddField(
            model_name='equipment_voa',
            name='description_type',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_voa_description_type, verbose_name='Описание типа'),
        ),
        migrations.AddField(
            model_name='equipment_voa',
            name='method_file_poverka',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_voa_method_file_poverka, verbose_name='Методика поверки/аттестации'),
        ),
        migrations.AlterField(
            model_name='equipment_io',
            name='image_of_equipment',
            field=models.ImageField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_io_img),
        ),
        migrations.AlterField(
            model_name='equipment_si',
            name='responsible_for_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reestr_people.omvoig_reestr'),
        ),
        migrations.AlterField(
            model_name='equipment_si',
            name='verification_file',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_verification, verbose_name='Файл поверки'),
        ),
        migrations.AlterField(
            model_name='equipment_vo',
            name='image_of_equipment',
            field=models.ImageField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_vo_img),
        ),
        migrations.AlterField(
            model_name='equipment_voa',
            name='image_of_equipment',
            field=models.ImageField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_voa_img),
        ),
        migrations.AlterField(
            model_name='equipment_voa',
            name='verification_file',
            field=models.FileField(blank=True, null=True, upload_to=reestrOMVOiG.models.directory_path_to_OMVOIG_voa_verification, verbose_name='Файл поверки'),
        ),
    ]
