# Generated by Django 3.1.1 on 2020-10-09 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reestr_people', '0005_ohti_reestr'),
        ('reestrOMVOiG', '0003_auto_20201008_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_si',
            name='responsible_for_use',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reestr_people.omvoig_reestr'),
        ),
    ]
