# Generated by Django 3.1.1 on 2020-10-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reestrOMVOiG', '0005_auto_20201009_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equip_si_part',
            options={'verbose_name': 'Запчасти', 'verbose_name_plural': 'Запчасти к Средствам измерения ОМВОиГ'},
        ),
        migrations.AlterField(
            model_name='equip_si_part',
            name='name_of_equip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='reestrOMVOiG.equipment_si'),
        ),
        migrations.CreateModel(
            name='Equip_IO_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_part', models.CharField(default='', max_length=150, verbose_name='Наименование запчасти(расходного материала):')),
                ('fact_number', models.CharField(default='', max_length=150, verbose_name='Заводской номер (расходного материала):')),
                ('part_image', models.ImageField(blank=True, null=True, upload_to='images/omvoig_IO/parts/')),
                ('part_docum', models.FileField(blank=True, null=True, upload_to='images/omvoig_IO/parts/documents/', verbose_name='Файл')),
                ('name_of_equip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='reestrOMVOiG.equipment_io')),
            ],
            options={
                'verbose_name': 'Запчасти',
                'verbose_name_plural': 'Запчасти к Испытательному оборудованию ОМВОиГ',
            },
        ),
    ]
