# Generated by Django 3.1.1 on 2020-10-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reestrOMVOiG', '0006_auto_20201011_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip_VOA_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_part', models.CharField(default='', max_length=150, verbose_name='Наименование запчасти(расходного материала):')),
                ('fact_number', models.CharField(default='', max_length=150, verbose_name='Заводской номер (расходного материала):')),
                ('part_image', models.ImageField(blank=True, null=True, upload_to='images/omvoig_VOA/parts/')),
                ('part_docum', models.FileField(blank=True, null=True, upload_to='images/omvoig_VOA/parts/documents/', verbose_name='Файл')),
                ('name_of_equip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='reestrOMVOiG.equipment_voa')),
            ],
            options={
                'verbose_name': 'Запчасти',
                'verbose_name_plural': 'Запчасти к Оборудованию вне области аккредитации ОМВОиГ',
            },
        ),
        migrations.CreateModel(
            name='Equip_VO_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_part', models.CharField(default='', max_length=150, verbose_name='Наименование запчасти(расходного материала):')),
                ('fact_number', models.CharField(default='', max_length=150, verbose_name='Заводской номер (расходного материала):')),
                ('part_image', models.ImageField(blank=True, null=True, upload_to='images/omvoig_VO/parts/')),
                ('part_docum', models.FileField(blank=True, null=True, upload_to='images/omvoig_VO/parts/documents/', verbose_name='Файл')),
                ('name_of_equip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='reestrOMVOiG.equipment_vo')),
            ],
            options={
                'verbose_name': 'Запчасти',
                'verbose_name_plural': 'Запчасти к Вспомогательному оборудованию ОМВОиГ',
            },
        ),
    ]
